# Generated by Django 5.2 on 2025-05-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Admin", "0001_initial"),
        ("pemilik", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PenghuniKost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("no_hp", models.IntegerField()),
                ("preferensi_lokasi", models.CharField(max_length=255)),
                ("preferensi_harga", models.IntegerField()),
                ("preferensi_fasilitas", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_booking", models.IntegerField()),
                ("tanggal_booking", models.DateField()),
                ("metode_pembayaran", models.CharField(max_length=255)),
                (
                    "kost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pemilik.kost"
                    ),
                ),
                (
                    "penghuni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pencari.penghunikost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pembayaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah", models.IntegerField()),
                ("tanggal_pembayaran", models.DateField()),
                ("metode_pembayaran", models.CharField(max_length=20)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pencari.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notifikasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pesan", models.CharField(max_length=255)),
                ("tanggal_kirim", models.DateField()),
                (
                    "penghuni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pencari.penghunikost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("komentar", models.CharField(max_length=255)),
                ("rating", models.IntegerField()),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.admin"
                    ),
                ),
                (
                    "penghuni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pencari.penghunikost",
                    ),
                ),
            ],
        ),
    ]
