# Generated by Django 5.2 on 2025-05-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pencari", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="penghunikost",
            name="preferensi_fasilitas",
        ),
        migrations.RemoveField(
            model_name="penghunikost",
            name="preferensi_harga",
        ),
        migrations.RemoveField(
            model_name="penghunikost",
            name="preferensi_lokasi",
        ),
    ]
