# Generated by Django 5.2 on 2025-05-10 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pencari", "0002_remove_penghunikost_preferensi_fasilitas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="penghunikost",
            name="password",
            field=models.CharField(default="password", max_length=128),
        ),
        migrations.AddField(
            model_name="penghunikost",
            name="username",
            field=models.CharField(default="user", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="penghunikost",
            name="no_hp",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\d{12,13}$")
                ],
            ),
        ),
    ]
