# Generated by Django 5.2 on 2025-05-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pencari", "0003_penghunikost_password_penghunikost_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penghunikost",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="penghunikost",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
