# Generated by Django 5.2 on 2025-05-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pencari', '0005_alter_penghunikost_no_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tanggal_masuk',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='metode_pembayaran',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status_booking',
            field=models.IntegerField(choices=[(0, 'Menunggu'), (1, 'Diterima'), (2, 'Ditolak')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tanggal_booking',
            field=models.DateField(auto_now_add=True),
        ),
    ]
