# Generated by Django 5.2 on 2025-05-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pencari', '0006_booking_tanggal_masuk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='metode_pembayaran',
        ),
    ]
