# Generated by Django 5.2 on 2025-05-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pencari', '0007_remove_booking_metode_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_booking',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
