# Generated by Django 5.2 on 2025-06-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pencari', '0008_alter_booking_status_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
