# Generated by Django 5.2 on 2025-06-01 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pencari', '0009_reviewrating_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
