# Generated by Django 5.2 on 2025-06-01 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0017_pemilikkost_email'),
        ('pencari', '0011_alter_reviewrating_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='kost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='pemilik.kost'),
            preserve_default=False,
        ),
    ]
