# Generated by Django 5.2.2 on 2025-06-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pencari', '0012_reviewrating_kost'),
    ]

    operations = [
        migrations.AddField(
            model_name='penghunikost',
            name='email_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='penghunikost',
            name='mobile_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
