# Generated by Django 5.2 on 2025-05-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("no_hp", models.CharField(max_length=255)),
            ],
        ),
    ]
