# Generated by Django 5.2 on 2025-05-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PemilikKost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("no_hp", models.IntegerField()),
                ("alamat_kost", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Kost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("alamat", models.CharField(max_length=255)),
                ("harga", models.IntegerField()),
                ("fasilitas", models.CharField(max_length=255)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.admin"
                    ),
                ),
                (
                    "pemilik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pemilik.pemilikkost",
                    ),
                ),
            ],
        ),
    ]
