# Generated by Django 5.2 on 2025-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pemilik", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kost",
            name="gambar",
            field=models.ImageField(blank=True, null=True, upload_to="gambar_kost/"),
        ),
        migrations.AddField(
            model_name="kost",
            name="lokasi",
            field=models.URLField(
                blank=True,
                help_text="Masukkan URL Google Maps",
                max_length=500,
                null=True,
            ),
        ),
    ]
