# Generated by Django 5.2 on 2025-05-06 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pemilik", "0002_kost_gambar_kost_lokasi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kost",
            name="gambar",
        ),
        migrations.CreateModel(
            name="KostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gambar", models.ImageField(upload_to="gambar_kost/")),
                (
                    "kost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gambar_kost",
                        to="pemilik.kost",
                    ),
                ),
            ],
        ),
    ]
