# Generated by Django 5.2 on 2025-05-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pemilik", "0003_remove_kost_gambar_kostimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="pemilikkost",
            name="password",
            field=models.CharField(default="defaultpassword", max_length=128),
        ),
        migrations.AddField(
            model_name="pemilikkost",
            name="username",
            field=models.CharField(default="defaultuser", max_length=255, unique=True),
        ),
    ]
