# Generated by Django 5.2 on 2025-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0003_remove_kost_gambar_kostimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kostimage',
            name='gambar',
        ),
        migrations.AddField(
            model_name='kost',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kost',
            name='tipe_kost',
            field=models.CharField(choices=[('Kost Putra', 'Kost Putra'), ('Kost Putri', 'Kost Putri'), ('Campur', 'Campur')], default='Kost Putra', max_length=255),
        ),
        migrations.AddField(
            model_name='kostimage',
            name='gambar1',
            field=models.ImageField(default='default.jpg', upload_to='gambar_kost/'),
        ),
        migrations.AddField(
            model_name='kostimage',
            name='gambar2',
            field=models.ImageField(default='default.jpg', upload_to='gambar_kost/'),
        ),
        migrations.AddField(
            model_name='kostimage',
            name='gambar3',
            field=models.ImageField(default='default.jpg', upload_to='gambar_kost/'),
        ),
        migrations.AddField(
            model_name='kostimage',
            name='gambar4',
            field=models.ImageField(default='default.jpg', upload_to='gambar_kost/'),
        ),
        migrations.AddField(
            model_name='kostimage',
            name='gambar5',
            field=models.ImageField(default='default.jpg', upload_to='gambar_kost/'),
        ),
    ]
