# Generated by Django 5.2 on 2025-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pemilik", "0004_pemilikkost_password_pemilikkost_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pemilikkost",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="pemilikkost",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
