# Generated by Django 5.2 on 2025-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0004_remove_kostimage_gambar_kost_rating_kost_tipe_kost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='tipe_kost',
            field=models.CharField(choices=[('Putra', 'Putra'), ('Putri', 'Putri'), ('Campur', 'Campur')], default='Kost Putra', max_length=255),
        ),
    ]
