# Generated by Django 5.2 on 2025-05-10 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pemilik", "0005_alter_pemilikkost_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pemilikkost",
            name="no_hp",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\d{12,13}$")
                ],
            ),
        ),
    ]
