# Generated by Django 5.2 on 2025-05-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0005_alter_kost_tipe_kost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='tipe_kost',
            field=models.CharField(choices=[('Putra', 'Putra'), ('Putri', 'Putri'), ('Campur', 'Campur')], default='Putra', max_length=255),
        ),
    ]
