# Generated by Django 5.2 on 2025-05-10 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0006_alter_kost_tipe_kost'),
    ]

    operations = [
        migrations.AddField(
            model_name='kost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
