# Generated by Django 5.2 on 2025-05-10 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pemilik", "0006_alter_pemilikkost_no_hp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pemilikkost",
            name="no_hp",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Nomor HP harus terdiri dari 12–13 digit angka.",
                        regex="^\\d{12,13}$",
                    )
                ],
            ),
        ),
    ]
