# Generated by Django 5.2 on 2025-05-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0007_kost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
