# Generated by Django 5.2 on 2025-05-21 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0008_alter_kost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilikkost',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$', max_length=128),
        ),
        migrations.AddField(
            model_name='pemilikkost',
            name='username',
            field=models.CharField(default='adminnnnnnn', max_length=255),
        ),
        migrations.AlterField(
            model_name='pemilikkost',
            name='no_hp',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Nomor HP harus terdiri dari 12–13 digit angka.', regex='^\\d{12,13}$')]),
        ),
    ]
