# Generated by Django 5.2 on 2025-05-25 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pemilik', '0010_alter_pemilikkost_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilikkost',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='pemilikkost',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='pemilikkost',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='pemilikkost',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='pemilikkost',
            name='no_hp',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Nomor HP harus terdiri dari 12–13 digit.', regex='^\\d{12,13}$')]),
        ),
        migrations.AlterField(
            model_name='pemilikkost',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='pemilikkost',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
