# Generated by Django 5.2 on 2025-05-25 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0011_pemilikkost_groups_pemilikkost_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemilikkost',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='pemilikkost',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pemilikkost',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pemilikkost',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='pemilikkost',
            name='no_hp',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Nomor HP harus terdiri dari 12–13 digit angka.', regex='^\\d{12,13}$')]),
        ),
        migrations.AlterField(
            model_name='pemilikkost',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pemilikkost',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
