# Generated by Django 5.2 on 2025-05-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0012_remove_pemilikkost_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
