# Generated by Django 5.2 on 2025-05-25 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('pemilik', '0013_kost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.admin'),
        ),
    ]
