# Generated by Django 5.2 on 2025-05-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0014_alter_kost_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='kost',
            name='status_booking',
            field=models.CharField(choices=[('tidak tersedia', 'Tidak Tersedia'), ('tersedia', 'Tersedia')], default='tersedia', max_length=20),
        ),
    ]
