# Generated by Django 5.2 on 2025-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0015_kost_status_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='status_booking',
            field=models.CharField(choices=[('tidak tersedia', 'Tidak Tersedia'), ('tersedia', 'Tersedia'), ('pending', 'Pending')], default='tersedia', max_length=20),
        ),
    ]
