# Generated by Django 5.2 on 2025-06-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0016_alter_kost_status_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilikkost',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
