# Generated by Django 5.2 on 2025-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilik', '0017_pemilikkost_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kost',
            name='deskripsi',
            field=models.TextField(default='Deskripsi belum tersedia'),
        ),
    ]
